# Generated by Django 4.2.11 on 2024-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
